---
- hosts: all
  become: true
  gather_facts: true
  vars_files:
    - vars/vars.yml
    - vars/enc_vars.yml
  tasks:
    - include_tasks: tasks/qemu-agent.yml
    - include_tasks: tasks/9p-mounts.yml
    - include_tasks: tasks/sshd.yml
    - include_tasks: tasks/docker.yml
    - include_tasks: tasks/join-swarm.yml
    - include_tasks: tasks/portainer.yml
  handlers:
    - include: handlers/mount.yml
