---
- name: Enable borgmatic timer
  listen: enable_borgmatic_timer
  ansible.builtin.service:
    name: borgmatic.timer
    state: started
    enabled: true

- name: Reload systemctl
  listen: reload_systemctl
  ansible.builtin.systemd_service:
    daemon_reload: true
