---
- name: Start NZBGet
  ansible.builtin.service:
    name: nzbget
    state: started

- name: Start Transmission
  ansible.builtin.service:
    name: transmission
    state: started

- name: Start Sonarr
  ansible.builtin.service:
    name: sonarr
    state: started

- name: Start Radarr
  ansible.builtin.service:
    name: radarr
    state: started
