---
- name: Stop Sonarr
  ansible.builtin.service:
    name: sonarr
    state: stopped
  notify:
    - Start Sonarr
  when: "sonarr/{{ item }} is file"
  with_items:
    - sonarr.db
    - sonarr.db-journal
    - nzbdrone.db
    - nzbdrone.db-journal
    - config.xml

- name: Restore Sonarr data
  ansible.builtin.copy:
    src: "sonarr/{{ item }}"
    dest: /var/lib/sonarr/
    backup: yes
    mode: 0644
    owner: sonarr
    group: sonarr
  when: "sonarr/{{ item }} is file"
  with_items:
    - sonarr.db
    - sonarr.db-journal
    - nzbdrone.db
    - nzbdrone.db-journal
    - config.xml
