---
- hosts: all
  become: true
  vars:
    rds__src_repo: https://github.com/coaxial/docker-downloader.git
    rds__src_repo_version: deploy
    downloader__media_path: /media/storage/nas
    downloader__scratch_path: /media/scratch/downloader
    downloader__tarsnap_key_path: ./files/tarsnap.key
    downloader__tarsnap_key_dest: /opt/docker-downloader/files/

  pre_tasks:
    - name: Ensure required directories exist for the docker volumes
      file:
        src: "{{ item.src }}"  # symlink
        dest: "{{ item.dest }}"  # where the symlink points to
        state: link
      with_items:
        - src: "{{ downloader__media_path }}/TV"
          dest: /srv/tv_shows
        - src: "{{ downloader__media_path }}/Movies"
          dest: /srv/movies
        - src: "{{ downloader__scratch_path }}"
          dest: /srv/downloads

  roles:
    - ../deploy-docker-service

  post_tasks:
    - name: Copy tarsnap key over
      copy:
        src: "{{ downloader__tarsnap_key_path }}"
        dest: "{{ downloader__tarsnap_key_dest }}"
        owner: root
        group: root
        mode: 0600

    # nginx returns 502 for some services if it isn't destroyed and rebuilt
    - name: Destroy and rebuild proxy container
      docker_service:
        project_src: "{{ dest_path }}"
        services:
          - proxy
        recreate: always
        state: present
      when: rds__files_copied.changed or rds__git_clone.changed
