---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  # ansible-lint can't deal with vault passwords
  ansible-playbook --syntax-check --vault-password-file .vault_pass playbook.yml
  flake8
platforms:
  - name: ${MOLECULE_DISTRO:-ubuntu2004}
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  options:
    vault_password_file: .vault_pass
verifier:
  name: testinfra
scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    # - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
