---
# NOTE: Use this incantation to create the VM (or add it to
# /etc/pve/qemu-server/<id>.conf):
# args: -virtfs local,security_model=passthrough,id=fsdev0,path=/mnt/antigua/docker_ct_data,mount_tag=ct_data
- name: Add 9P mount to fstab
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: /^ct_data.*/
    line: "ct_data /ct_data        9p      trans=virtio,version=9p2000.L,_netdev,msize=104857600   0       0"
    state: present
  notify:
    - create_9p_dir
    - mount_fstab
