---
# If Galaxy is down, use:
# - src: https://example.org/user/repo.git
#   name: user.repo
# Otherwise:
# - src: coaxial.base
- src: https://github.com/coaxial/ansible-role-base
  name: coaxial.base
- src: https://github.com/coaxial/ansible-role-jellyfin
  name: coaxial.jellyfin
