---
# Handlers are triggered by a task and executed at the end of a role
# execution, they are useful for restarting and reloading services, or
# any other action that you only want to be performed once, but that
# might have multiple triggers
