---
- hosts: all
  become: true
  vars_files:
    - vars/vars.yml
    - vars/enc_vars.yml
  handlers:
    - include: handlers/main.yml
  roles:
    # - coaxial.base
    # - coaxial.servarr
  pre_tasks:
    - include: tasks/dirs.yml
  tasks:
    - include: tasks/nzbget.yml
    - include: tasks/transmission.yml
    # - include_tasks: tasks/sonarr.yml
    # - include_tasks: tasks/radarr.yml
    # - include_tasks: tasks/backup.yml
