- name: Set destination directory name as fact (local)
  set_fact:
    dest_path: "/opt/{{ rds__src_path | basename | lower | regex_replace('\\s, -') }}"
  when: rds__src_path is defined

- name: Set destination directory name as fact (git)
  set_fact:
    dest_path: "/opt/{{ rds__src_repo | regex_search('([\\w\\d\\-]+)\\.git') | regex_replace('\\.git', '') }}"
  when: rds__src_repo is defined

- name: Copy project files over (local)
  copy:
    src: "{{ rds__src_path }}"
    dest: /opt
    force: true
    owner: root
    group: root
    mode: 0644
  when: rds__src_path is defined
  # start service at end of play so that service specific tasks can be
  # performed (eg. copy the tarsnap key in place so that it's available when the
  # backup service starts)
  notify:
    - "start_service"

- name: Clone repo (git)
  git:
    repo: "{{ rds__src_repo }}"
    dest: "{{ dest_path }}"
    version: "{{ rds__src_repo_version | default('HEAD') }}"
  when: rds__src_repo is defined
  # start service at end of play so that service specific tasks can be
  # performed (eg. copy the tarsnap key in place so that it's available when the
  # backup service starts)
  notify:
    - "start_service"
