---
- hosts: all
  become: true
  gather_facts: false
  vars_files:
    - vars.yml
  vars:
    zfs_enable: true
    zpool_name: zdata1

  # bootstrap python2
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: bootstrap_python
      changed_when: bootstrap_python.stdout != ''
    - include: hostname.yml
    - setup:


  roles:
    - coaxial.base
    - angstwad.docker_ubuntu

  tasks:
    - include: refresh_apt_cache.yml
    # Waiting for https://github.com/ansible/ansible/issues/34546 to be
    # resolved
    # - include: ip.yml
    - include: file_server.yml
    - include: vm_host.yml
