---
- hosts: all
  become: true
  gather_facts: false
  vars_files:
    - vars/vars.yml
  vars:
    zfs_enable: true
    zpool_name: zdata1

  roles:
    - coaxial.raw-python
    - coaxial.base
    - angstwad.docker_ubuntu

  tasks:
    - include: tasks/refresh_apt_cache.yml
    # Waiting for https://github.com/ansible/ansible/issues/34546 to be
    # resolved
    # - include: tasks/ip.yml
    - include: tasks/file_server.yml
    - include: tasks/vm_host.yml
    - include_role:
        name: coaxial.lxd
    - include: tasks/send_mail.yml
    - include: tasks/lxd_profile.yml
    - include_role:
        name: coaxial.create-lxd-container
      with_items: "{{ cc__containers }}"
    - include: tasks/node-exporter.yml

  handlers:
    - include: handlers/postfix.yml
    - include: handlers/zed.yml
