---
- hosts: all
  become: true
  gather_facts: false
  vars_files:
    - vars/vars.yml
  vars:
    zfs_enable: true
    zpool_name: zdata1

  # bootstrap python2
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
      register: bootstrap_python
      changed_when: bootstrap_python.stdout != ''
    - include: tasks/hostname.yml
    - setup:


  roles:
    - coaxial.base
    - angstwad.docker_ubuntu

  tasks:
    - include: tasks/refresh_apt_cache.yml
    # Waiting for https://github.com/ansible/ansible/issues/34546 to be
    # resolved
    # - include: tasks/ip.yml
    - include: tasks/file_server.yml
    - include: tasks/vm_host.yml
    - include_role:
        name: coaxial.lxd
    - include: tasks/send_mail.yml
    - include: tasks/lxd_profile.yml
    - include_role:
        name: coaxial.create-lxd-container
      with_items: "{{ cc__containers }}"

  handlers:
    - include: handlers/postfix.yml
    - include: handlers/zed.yml
