---
- src: coaxial.raw-python
- src: coaxial.base
  version: v1.2.1
- src: coaxial.lxd
- src: angstwad.docker_ubuntu
- src: coaxial.create-lxd-container
- src: coaxial.firewall_rule
- src: coaxial.node_exporter
