# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.network "private_network", ip: "192.168.66.10"
  config.vm.synced_folder "./", "/media/storage/nas"
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = 'playbook.yml'
    ansible.verbose = false
  end
end
