---
- hosts: all
  become: true
  gather_facts: false
  vars_files:
    - vars.yml
  vars:
    bootstrap_host: true  # enable if host needs python, firewall, etc.
    pip_install_packages:
      - name: docker
      - name: docker-compose
    td__restore_latest_backup: true
    td__enable_backups: true
    td__fetch_client_files: true

  tasks:
    - name: Configure host
      include_role:
        name: "{{ rolevar.name }}"
      when: |
        (rolevar.when is defined and rolevar.when)
        or rolevar.when is not defined
      with_items:
        - name: coaxial.raw-python
          when: "{{ bootstrap_host }}"
        - name: coaxial.base
          when: "{{ bootstrap_host }}"
        - name: geerlingguy.pip
        - name: geerlingguy.docker
        - name: coaxial.taskserver
      loop_control:
        loop_var: rolevar
