---
- name: Add swap
  command: "fallocate -l {{ ansible_memtotal_mb }}M /swapfile"
  args:
    creates: /swapfile
  register: swap_create

- name: Set permissions on swapfile
  file:
    path: /swapfile
    mode: 0600
    owner: root
    group: root

- name: Mark swap
  command: "mkswap /swapfile"
  when: swap_create.changed

- name: Enable swap for session
  command: "swapon /swapfile"
  when: swap_create.changed

- name: Make swap file permanent
  lineinfile:
    path: /etc/fstab
    state: present
    regexp: '^\/swapfile'
    line: '/swapfile  none  swap  sw  0 0'

- name: Set swappiness
  lineinfile:
    path: '/etc/sysctl.conf'
    state: present
    regexp: '^vm\.swappiness'
    line: 'vm.swappiness=10'

- name: Set cache pressure
  lineinfile:
    path: '/etc/sysctl.conf'
    state: present
    regexp: '^vm\.vfs_cache_pressure'
    line: 'vm.vfs_cache_pressure=50'

