---
- name: Install zfs
  package:
    name: zfsutils-linux
    state: present
  when: zfs_enable

- name: Check if pool already imported
  shell: "zpool status {{ zpool_name }} >/dev/null 2>&1 && echo 'True' || echo 'False'"
  register: zpool_imported_test_cmd
  changed_when: false

- name: Save pool import status as fact
  set_fact:
    zpool_already_imported: "{{ zpool_imported_test_cmd.stdout |bool }}"

- name: Configure ZED
  template:
    src: templates/zed.rc.j2
    dest: /etc/zfs/zed.d/zed.rc
    mode: "0600"
    owner: root
    group: root
  notify: restart zed
  when: zfs_enable

- name: Import zfs pool
  command: "zpool import {{ zpool_name }}"
  when: zfs_enable and not zpool_already_imported

- name: Configure zfs mount points
  zfs:
    name: "{{ item.name }}"
    extra_zfs_properties:
      mountpoint: "{{ item.mountpoint }}"
      canmount: "{{ item.canmount }}"
    state: present
  when: zfs_enable and not zpool_already_imported
  with_items: "{{ zfs_datasets }}"

- name: Configure nfs sharing
  zfs:
    name: "{{ zpool_name }}/storage/nas"
    extra_zfs_properties:
      sharenfs: "no_subtree_check,all_squash,rw=@{{ ansible_default_ipv4.network }}/24"
    state: present
  when: zfs_enable and not zpool_already_imported

- name: Enable zfs shares
  command: "zfs share -a"
  when: zfs_enable and not zpool_already_imported
